import Head from "next/head";
import { Poppins, Underdog } from "next/font/google";
import Layout from "@/components/Layout";
import Navbar from "@/components/Navbar";
import Detail from "@/components/detail";
import Footer from "@/components/Footer";
import usePropertyDataStore from "@/hooks/usePropertyData";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export default function Subpage() {
  const router = useRouter();

  const propertyDetail = usePropertyDataStore((state) => state.propertyDetail);

  const fetchPropertyDetail = usePropertyDataStore(
    (state) => state.fetchPropertyDetail
  );
  useEffect(() => {
    const { id } = router.query;
    if (id) {
      const singleId = Array.isArray(id) ? id.join("") : id;
      fetchPropertyDetail(singleId);
    }
  }, [fetchPropertyDetail, router.query]);

  return (
    <>
      <Head>
        <title>{propertyDetail?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${poppins.className}`}>
        <Layout>
          <Navbar />
        </Layout>
        <Detail />
        <Footer />
      </main>
    </>
  );
}
