import Head from "next/head";
import { Poppins } from "next/font/google";
import Layout from "@/components/Layout";
import Navbar from "@/components/Navbar";
import Hero from "@/components/home/Hero";
import Section from "@/components/home/Section";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Future Living</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${poppins.className}`}>
        <Layout>
          <Navbar />
        </Layout>
        <Hero />
        <Section />
      </main>
    </>
  );
}
