import Head from "next/head";
import Layout from "@/components/Layout";
import Navbar from "@/components/Navbar";
import Hero from "@/components/home/Hero";
import Section from "@/components/home/Section";

export default function Home() {
  return (
    <>
      <Head>
        <title>Future Living</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Navbar />
        </Layout>
        <Hero />
        <Section />
      </main>
    </>
  );
}
